### ISSUE TITLE
Issue between nlmixr2 and rstan

### ISSUE THREAD

**Issue by Marie-Karelle** [nlmixr2/nlmixr2#253] opened 2024-08-06 14:53 UTC
Dear all,

I am using nlmixr to fit PK model. When I use it alone, there is no problem. But when I compile a stan model to also fit other models with rstan, then the same nlmixr call doesn't work anymore...
I create a simple example from the website example : 
library(nlmixr2)

```r
## The basic model consists of an ini block that has initial estimates
one.compartment <- function() {
  ini({
    tka <- log(1.57); label("Ka")
    tcl <- log(2.72); label("Cl")
    tv <- log(31.5); label("V")
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  # and a model block with the error specification and model specification
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) <- -ka * depot
    d/dt(center) <- ka * depot - cl / v * center
    cp <- center / v
    cp ~ add(add.sd)
  })
}

## The fit is performed by the function nlmixr/nlmixr2 specifying the model, data and estimate
fit <- nlmixr2(one.compartment, theo_sd,  est="saem", saemControl(print=0))


library(rstan)
test_stan_model = "data {
  int n_pat;
  int nb_doses;
  int y[n_pat];
  int dose_donnees[n_pat];
  vector[nb_doses] wm;
}
transformed data {
  vector[nb_doses] tdoses;
  tdoses = log(wm ./ (1-wm));
}
parameters {
  real alpha;
  real<lower=0> beta;
}
transformed parameters { 
  vector[nb_doses] ptox;
  ptox = exp(alpha + beta * tdoses) ./ (1 + exp(alpha + beta * tdoses));
  
}
model {
  alpha ~ normal(0, sqrt(10));
  beta ~ exponential(1);
  for(i in 1:n_pat){
    y[i] ~ bernoulli(ptox[dose_donnees[i]]);
  }
}"
model_test = stan_model(model_code = test_stan_model)


fit <- nlmixr2(one.compartment, theo_sd,  est="saem", saemControl(print=0))
```

I have a very long error, with the main following error:
error building model

It seems that the error is not reproductible on my friend's computer. So it may be a version issue. I will investigate.

Thanks for your help !
Best regards

**Comment by jhjourdan** [comment] 2024-08-06 18:57
As you write, `cmath` is a standard C++ header, but not a C header. It is expected that the C compiler complains if one is trying to include it. (It turns out that `cmath` is C++'s name for C's `math.h`, but the name `cmath` should not be used from a C file.)


What's weird here is that the compiler which is used is the C compiler,but it seems that it uses options of the C++ compiler, and headers of C++ libraries. What's the expected behavior here?

**Comment by jhjourdan** [comment] 2024-08-06 21:06
It seems like `rstan` sets some environment variables which break `nlmixr2`. If I run the following code:

```
Sys.unsetenv(c("PKG_CPPFLAGS", "PKG_LIBS", "USE_CXX17"))
```

before calling nlmixr2, then the issue disappears. I'm posting an issue on rstan's bug tracker.

**Comment by Marie-Karelle** [comment] 2024-08-06 21:08
Thanks a lot to both of you !!

**Comment by mattfidler** [comment] 2024-08-08 01:41
Thanks @Marie-Karelle  and @jhjourdan 

I am closing this for now.

**Closed** 2024-08-08 01:41 UTC
